# Generated by Django 5.1.7 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cards',
            field=models.JSONField(blank=True),
        ),
    ]
